# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  byfn:

services:
  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      # - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.government.example.com:7051
      - CORE_PEER_LOCALMSPID=governmentMSP
      - CORE_PEER_TLS_ENABLED=false
     
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../../chaincode/:/opt/gopath/src/github.com/chaincode
        - ../crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ../scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ../network-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/network-config
   # depends_on:
        #- orderer.example.com
        #- peer0.cama.example.com
        #- peer1.cama.example.com
        #- peer0.subadmin.example.com
        #- peer1.subadmin.example.com
        #- peer0.stakeholders.example.com
        #- peer1.stakeholders.example.com
    #   - peer0.bm.example.com
    #   - peer1.bm.example.com
    #   - peer0.dl.example.com
    #   - peer1.dl.example.com
    #   - peer0.im.example.com
    #   - peer1.im.example.com
    #   - peer0.investor.example.com
    #   - peer1.investor.example.com
    #   - peer0.pc.example.com
    #   - peer1.pc.example.com
    #   - peer0.producer.example.com
    #   - peer1.producer.example.com
    #   - peer0.sp.example.com
    #   - peer1.sp.example.com
    #   - peer0.talent.example.com
    #   - peer1.talent.example.com
    networks:
      - byfn
