

version: '2'
services:
  orderer:
    image: hyperledger/fabric-orderer:1.4.0
    environment:
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${CORE_PEER_NETWORKID}_byfn
      - ORDERER_HOME=/var/hyperledger/orderer
      - ORDERER_GENERAL_LOGLEVEL=DEBUG
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_LEDGERTYPE=ram
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/msp
      - CONFIGTX_ORDERER_ORDERERTYPE=solo
      - CONFIGTX_ORDERER_BATCHSIZE_MAXMESSAGECOUNT=10
      - CONFIGTX_ORDERER_BATCHTIMEOUT=2s
      - CONFIGTX_ORDERER_ADDRESSES=[127.0.0.1:7050]
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=false
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/tls/ca.crt]
      #- ORDERER_TLS_CLIENTAUTHREQUIRED=${ORDERER_TLS_CLIENTAUTHREQUIRED}
      - ORDERER_TLS_CLIENTROOTCAS_FILES=/var/hyperledger/users/Admin@example.com/tls/ca.crt
      - ORDERER_TLS_CLIENTCERT_FILE=/var/hyperledger/users/Admin@example.com/tls/client.crt
      - ORDERER_TLS_CLIENTKEY_FILE=/var/hyperledger/users/Admin@example.com/tls/client.key
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    volumes:
      - ../network-config/:/var/hyperledger/configs
      - ../crypto-config/ordererOrganizations/example.com/users:/var/hyperledger/users
      - ../network-config/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    #- ../crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
    #- ../crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/:/var/hyperledger/orderer/tls
    #- orderer.example.com:/var/hyperledger/production/orderer



# orderer:
#         image: hyperledger/fabric-orderer
#         environment:
#             - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${CORE_PEER_NETWORKID}_behave
#             - ORDERER_HOME=/var/hyperledger/orderer
#             - ORDERER_GENERAL_LOGLEVEL=debug
#             - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/msp
#             - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
#             - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
#             - ORDERER_GENERAL_LISTENPORT=7050
#             - ORDERER_GENERAL_LEDGERTYPE=ram
#             - ORDERER_GENERAL_GENESISMETHOD=file
#             - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/configs/orderer.block
#             - CONFIGTX_ORDERER_ORDERERTYPE=solo
#             - CONFIGTX_ORDERER_BATCHSIZE_MAXMESSAGECOUNT=${CONFIGTX_ORDERER_BATCHSIZE_MAXMESSAGECOUNT}
#             - CONFIGTX_ORDERER_BATCHTIMEOUT=${CONFIGTX_ORDERER_BATCHTIMEOUT}
#             - CONFIGTX_ORDERER_ADDRESSES=[127.0.0.1:7050]
#             # TLS settings
#             - ORDERER_GENERAL_TLS_ENABLED=${ORDERER_GENERAL_TLS_ENABLED}
#             - ORDERER_GENERAL_TLS_PRIVATEKEY=${ORDERER_GENERAL_TLS_PRIVATEKEY}
#             - ORDERER_GENERAL_TLS_CERTIFICATE=${ORDERER_GENERAL_TLS_CERTIFICATE}
#             - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/tls/ca.crt]
#             - ORDERER_TLS_CLIENTAUTHREQUIRED=${ORDERER_TLS_CLIENTAUTHREQUIRED}
#             - ORDERER_TLS_CLIENTROOTCAS_FILES=/var/hyperledger/users/Admin@example.com/tls/ca.crt
#             - ORDERER_TLS_CLIENTCERT_FILE=/var/hyperledger/users/Admin@example.com/tls/client.crt
#             - ORDERER_TLS_CLIENTKEY_FILE=/var/hyperledger/users/Admin@example.com/tls/client.key
#         volumes:
#             - ../config/:/var/hyperledger/configs
#             - ../crypto-config/ordererOrganizations/example.com/users:/var/hyperledger/users
#         working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
#         command: orderer
#         ports:
#           - '7050'
